# test.yml
#
# Copyright (C) 2022 ViliusSutkus89.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: ADB and debug keystore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.android/adb*
            ~/.android/debug.keystore
          key: adb-and-debug-keystore-${{ secrets.CACHE_KEY_SUFFIX }}

      - uses: android-actions/setup-android@v2

      - run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: adb-and-debug-keystore
          path: |
            ~/.android/adb*
            ~/.android/debug.keystore

      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: app/build

      - run: ls -lhaR
      - run: ls -lhaR ~/.android

  test:
    needs: build
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            api-level: 16
            api-type-target: default
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - uses: actions/download-artifact@v3
        with:
          name: adb-and-debug-keystore
          path: ~/.android
      - run: ls -lhaR ~/.android

      - uses: actions/download-artifact@v3
        with:
          name: app-build
          path: app/build

      - name: Android Virtual Device (AVD) cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: ~/.android/avd/*
          key: avd-${{ matrix.arch }}-${{ matrix.api-level }}-${{ matrix.api-type-target }}-${{ secrets.CACHE_KEY_SUFFIX }}

      - uses: android-actions/setup-android@v2

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          script: echo "Generated AVD snapshot for caching."

      - run: ls -lhaR

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          script: time ./gradlew connectedCheck
